In [2]:
#pytorch 프레임워크 불러오는 부분
import torch
import torchvision # image processing에 특화된 라이브러리
import torch.nn as nn
import torchvision.transforms as transforms # Data Augmentation
import numpy as np

In [5]:
X = torch.Tensor(2,3) # 2행 3열의 텐서를 하나 생성
X.shape
X.size()

X = torch.Tensor([[1,2,3],[4,5,6]])
X

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
'''
tensor() 인자값으로
data 
dtype
requires_grad : tensor에 대해서 미준 적용할지 여부

'''

x = torch.tensor(data=[2.0,3.0], requires_grad=True)
x

y=x**2
y

pred = 2*y + 3
pred

target = torch.tensor([3.0,4.0])
target

tensor([3., 4.])

In [ ]:
'''
위에서 나온 결과를 바탕으로
경사하강법을 이용해서
미분을 사용해서 Loss에 대한 책임을 묻겠다
기울기가 계산이 될 것이다. (미분 계산)
--> BackPropagation을 적용하려면 backward() 함수를 호출

Loss 를 줄여나가 보겠다
'''

In [9]:
loss = torch.sum(torch.abs(pred - target))
print('Loss', loss)

Loss tensor(25., grad_fn=<SumBackward0>)


In [10]:
loss.backward()

In [12]:
print(x.grad,pred.grad)

tensor([ 8., 12.]) None


<ipython-input-12-f0cd9ca8c1fa>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print(x.grad,pred.grad)


### Create Tensor ....Using NeuralNet

In [13]:
x = torch.randn(10,3)
y = torch.randn(10,2)
print(x)
print(y)

tensor([[ 0.7693, -1.1692,  2.2797],
        [-0.5503,  0.1910,  0.8762],
        [ 0.2180,  0.3191, -0.9460],
        [-0.4939,  1.5984, -0.4985],
        [ 0.4176, -0.0133, -1.1790],
        [-0.3029,  0.9968, -1.1196],
        [ 0.2542,  0.8102,  0.7982],
        [ 0.1203,  1.4062,  0.2247],
        [ 0.8972, -1.2176, -0.6021],
        [-0.6120, -0.1817,  2.3816]])
tensor([[-1.6135,  1.0082],
        [ 0.0819, -1.0606],
        [ 0.9675,  0.0838],
        [ 0.2345,  0.9511],
        [-0.4385,  1.0944],
        [-0.0496, -0.6176],
        [ 0.2707, -1.6344],
        [-1.2317, -1.4497],
        [ 0.7840, -0.5045],
        [ 0.5300, -1.3521]])


In [14]:
linear = nn.Linear(3,2)
print('w',linear.weight)
print('b',linear.bias)

w Parameter containing:
tensor([[-0.4674,  0.1884,  0.2226],
        [ 0.2411, -0.3035,  0.5255]], requires_grad=True)
b Parameter containing:
tensor([-0.0695,  0.5430], requires_grad=True)


In [19]:
# 객체출력, parameters()함수는 모델안의 학습의 주체인 w, b를 내포하고 있는 객체
# parameters() 함수는 w, b를 해킹한 함수이다.
print(linear.parameters())

# loss function을 미리 선정의 해두었다
loss_function = nn.MSELoss()

# optimizer(하산하는 방법)를 미리 정의
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

#위에서 만든 모델에 값을 입력...결과로 예측값이 나온다
pred = linear(x)

# 정답과 예측값을 이용해서 위에서 선정의한 Loss를 계산...L(W)
loss = loss_function(pred,y)
print('loss before step BackPropagation',loss.item())

<generator object Module.parameters at 0x000001D9D23C7F90>
loss before step BackPropagation 1.8234293460845947


In [20]:
'''
loss값이 나왔다는 것은
모델의 예측값에 대한 잘못을 정량화 했다는 것이다.

이 값을 바탕으로 BackPropagation을 하면 w,b에 대한 미분값
즉 얼마만큼 보정해야 하는지의 값이 나온다.
그 값을 이용해서 다시 하강(기울기 수정)하기 때문에
2번째에는 Loss가 줄어들어야 한다.
'''
loss.backward() #loss값에 대한 w의 책임을 묻는다...미분을 적용, grad
print('dL/dW', linear.weight.grad)
print('dL/db', linear.bias.grad)

dL/dW tensor([[-0.0890,  0.2034,  0.6488],
        [ 0.0186, -0.0780,  1.5086]])
dL/db tensor([0.0444, 0.9417])


In [22]:
optimizer.step() # 위에서 수정된 값으로 하강을 진행한다...학습을 한다

# 반복효과
pred = linear(x)
loss = loss_function(pred,y)

print('loss after step BackPropagation',loss.item())

loss after step BackPropagation 1.75180184841156
