### Numpy
    Numeric Python의 약자
    수학분야 관련 통계작업시 사용
    과학 계산 컴퓨팅, 데이터 분석에 필요한 기본적인 패키지
    
    Numpy배열은 리스트와 거의 흡사
    리스트보다 훨씬 빠르고 메모리 효율성이 높아서 성능상 우의를 차지한다
    
    Numpy는 사용에 앞서서 import 해서 사용해야 한다
    Numpy 배열 만드는 방법
    1) array() 사용
    2) random 모듈의 랜덤함수 사용

In [1]:
import numpy as np

#### np 배열 생성 | 리스트와 비교
    array() 함수 사용 | rand()

In [10]:
myList = [4,5,6,7]
myArr = np.array(myList)

print(myList)
print(myArr)

print(type(myList))
print(type(myArr))
'''
ndarray는 출력결과 [ ] 안에 값들이 나열되지만 ,로 구분되진 않는다.
ndarray타입
ndarray 클래스는 다차원행렬구조를 지원하는 Numpy의 핵심 클래스
'''

myList_sub=myList[1:3]
myList_sub[0] = -5
print(myList_sub)

myArr_sub=myArr[1:3]
myArr_sub[0] = -5
print(myArr_sub)

print('*'*30)
'''
리스트는 원본 안바뀐다. 변경되면 기존의 것을 카피해놓고 새로운걸 만든다.
반면에 np배열은 원본이 바뀐다.
이것이 리스트와 np배열의 가장 큰 차이점이다.
메모리 효율성과 연관되는 부분이다
'''
print(myList) #원본이 안바뀐다 (효울성 down)
print(myArr) #원본이 바뀐다 (효울성 up)

[4, 5, 6, 7]
[4 5 6 7]
<class 'list'>
<class 'numpy.ndarray'>
[-5, 6]
[-5  6]
******************************
[4, 5, 6, 7]
[ 4 -5  6  7]


In [17]:
# rand() 함수사용하기

a = np.random.rand(5) # 0~1사이의 랜덤한 값 5개 나열
print(a)
print(type(a))

b = np.random.randint(1,10,5) # 1~10사이의 랜덤한 값(int) 5개 나열
print(b)
print(type(b))

c = np.random.randn(10) # 가우시안(Gaussian) 표쥰분포의 랜덤한 값 10개 나열
print(c)
print(type(c))

[0.44016591 0.75571569 0.11394054 0.7709365  0.2864147 ]
<class 'numpy.ndarray'>
[9 4 2 1 4]
<class 'numpy.ndarray'>
[-0.93655843 -0.43098445 -0.53071619 -0.34941238 -0.07484989  0.25609798
 -1.43767166 -1.52406859 -0.48623367 -1.69422761]
<class 'numpy.ndarray'>


### np배열의 초기화
    zeros(),ones(),arange()...함수를 이용해서 배열 생성과 동시에 특정한 값으로 초기화 할 수 있다.

In [30]:
# 1.
az = np.zeros(10) # 0(실수(float)형)값으로 10개를 초기화
print(az)

# 2. 1값으로 이뤄진 크기가 10인 배열 생성
ao = np.ones(10)
print(ao)

# 3. 3 x 3 단위의 배열 생성
ae = np.eye(3)
print(ae)

# 4. arange()
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,10,2))

print('*'*30)
az7 = np.zeros(10)+7
print(az7)
ao7 = np.ones(10)*7
print(ao7)

af = np.full((7,5),23)
print(af)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2]
[3 4 5 6]
[3 5 7 9]
******************************
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
[[23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]]


### np배열과 리스트의 차이점
    1. np배열은 원본을 바로 바꿈으로써 메모리 효율성이 뛰어나다
    2. 리스트는 여러가지 자료형이 원소로 올수 있지만
       np배열은 한가지 자료형만 원소로 쓰일수 있다

In [36]:
L = [1,2,3,'4',4,'남승현'] # 리스트는 서로 다른 자료형이 원소로 올 수 있다, np배열은 이게 안된다
print(L)
print(type(L))

A = np.array(L) # 하나의 자료형만 저장 가능하다, capacity가 더 큰 자료형으로 변환한다.
print(A)
print(type(A))

A2 = np.array([1,6,3,9.3])
print(A2)

A3 = np.array([1,2,3,4],dtype='float')
print(A3)

A4 = np.array([1,2,3,4],dtype=np.float64)
print(A4)

[1, 2, 3, '4', 4, '남승현']
<class 'list'>
['1' '2' '3' '4' '4' '남승현']
<class 'numpy.ndarray'>
[1.  6.  3.  9.3]
[1. 2. 3. 4.]
[1. 2. 3. 4.]


### Numpy 배열에서 사용되는 함수, 속성
    ndim shape reshape() size type() dtype astype() 

In [39]:
arr1 = np.array([[1.0,2,3],[4,5,6]],dtype=np.int32)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
print(type(arr1))
print(np.ndim(arr1)) # 2차원
print(np.shape(arr1)) # 몇행 몇열 (2(행),3(열))
print(np.size(arr1)) # 갯수

print('*'*30)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
# print(arr1.type) 이건 에러
print(arr1.dtype)

print('*'*30)
# ndarray 안에 들어있는 모든 요소들의 타입을 한방에 바꿔버리는 기능...astype
arr1_1 = arr1.astype(np.float32)
print(arr1_1)
print(arr1_1.dtype)

print('*'*30)
arr2 = np.arange(32)
print(arr2)

arr2_1 = arr2.reshape(4,8)
print(arr2_1)

<class 'numpy.ndarray'>
2
(2, 3)
6
******************************
2
(2, 3)
6
int32
******************************
[[1. 2. 3.]
 [4. 5. 6.]]
float32
******************************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
